apiVersion: v1
kind: Service
metadata:
  name: sfsdb-edgex-adapter
  namespace: edgex
  labels:
    app: sfsdb-edgex-adapter
spec:
  type: ClusterIP
  selector:
    app: sfsdb-edgex-adapter
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP